/**
 * documents and document_links — Phase 6 ingestion (docs/PHASE-6-DESIGN.md §7).
 *
 * The rows describe a file; the file's bytes live in object storage under
 * `storage_key`. Nothing here ever sees the bytes, and nothing here decides
 * what a document means — that is the Read stage, and its answer arrives as an
 * opaque, already-validated `reading` value.
 *
 * Invalidate, never delete, as everywhere else: undo sets `t_invalid`.
 */
import type { Queryable } from "../client.js";

export type DocumentKind = "pdf" | "docx" | "xlsx" | "text" | "image";
export type DocumentLinkTargetKind = "person" | "organization" | "project";
export type DocumentLinkInference = "CONFIRMED" | "INFERRED" | "UNCERTAIN";

export interface Document {
  id: string;
  storage_key: string;
  /** As uploaded. Display only. */
  filename: string;
  kind: DocumentKind;
  content_type: string;
  byte_size: number;
  sha256: string;
  extracted_text: string | null;
  text_truncated: boolean;
  /** The Read stage's DocumentReading, or NULL when nothing could read it. */
  reading: unknown;
  read_failure: string | null;
  trace: unknown;
  source_message_id: string | null;
  t_valid: Date;
  t_invalid: Date | null;
  t_created: Date;
  t_expired: Date | null;
}

export interface CreateDocumentInput {
  /** Pre-generated by the caller so links in the same turn can reference it. */
  id?: string | null;
  storageKey: string;
  filename: string;
  kind: DocumentKind;
  contentType: string;
  byteSize: number;
  sha256: string;
  extractedText: string | null;
  textTruncated: boolean;
  reading: unknown;
  readFailure: string | null;
  trace: unknown;
  sourceMessageId: string | null;
}

export async function createDocument(tx: Queryable, input: CreateDocumentInput): Promise<Document> {
  const { rows } = await tx.query<Document>(
    `INSERT INTO documents
       (id, storage_key, filename, kind, content_type, byte_size, sha256, extracted_text,
        text_truncated, reading, read_failure, trace, source_message_id)
     VALUES (COALESCE($13::uuid, gen_random_uuid()), $1, $2, $3::document_kind, $4, $5, $6, $7,
             $8, $9::jsonb, $10, $11::jsonb, $12::uuid)
     RETURNING *`,
    [
      input.storageKey,
      input.filename,
      input.kind,
      input.contentType,
      input.byteSize,
      input.sha256,
      input.extractedText,
      input.textTruncated,
      input.reading === null || input.reading === undefined ? null : JSON.stringify(input.reading),
      input.readFailure,
      input.trace === null || input.trace === undefined ? null : JSON.stringify(input.trace),
      input.sourceMessageId,
      input.id ?? null,
    ],
  );
  return rows[0]!;
}

export async function getById(tx: Queryable, id: string): Promise<Document | null> {
  const { rows } = await tx.query<Document>(`SELECT * FROM documents WHERE id = $1`, [id]);
  return rows[0] ?? null;
}

/** The current document with these exact bytes, if any (§23 for files). */
export async function findCurrentBySha256(tx: Queryable, sha256: string): Promise<Document | null> {
  const { rows } = await tx.query<Document>(
    `SELECT * FROM documents_current WHERE sha256 = $1 ORDER BY t_created DESC LIMIT 1`,
    [sha256],
  );
  return rows[0] ?? null;
}

export async function invalidateDocument(tx: Queryable, id: string): Promise<void> {
  await tx.query(`UPDATE documents SET t_invalid = now() WHERE id = $1 AND t_invalid IS NULL`, [id]);
}

// ---------------------------------------------------------------------------
// links
// ---------------------------------------------------------------------------

export interface DocumentLink {
  id: string;
  document_id: string;
  target_kind: DocumentLinkTargetKind;
  target_id: string;
  inference_level: DocumentLinkInference;
  t_valid: Date;
  t_invalid: Date | null;
  t_created: Date;
  t_expired: Date | null;
}

export interface CreateDocumentLinkInput {
  documentId: string;
  targetKind: DocumentLinkTargetKind;
  targetId: string;
  inferenceLevel: DocumentLinkInference;
}

export async function createLink(tx: Queryable, input: CreateDocumentLinkInput): Promise<DocumentLink> {
  const { rows } = await tx.query<DocumentLink>(
    `INSERT INTO document_links (document_id, target_kind, target_id, inference_level)
     VALUES ($1::uuid, $2, $3::uuid, $4::inference_level)
     RETURNING *`,
    [input.documentId, input.targetKind, input.targetId, input.inferenceLevel],
  );
  return rows[0]!;
}

export async function findCurrentLink(
  tx: Queryable,
  documentId: string,
  targetKind: DocumentLinkTargetKind,
  targetId: string,
): Promise<DocumentLink | null> {
  const { rows } = await tx.query<DocumentLink>(
    `SELECT * FROM document_links_current
      WHERE document_id = $1 AND target_kind = $2 AND target_id = $3`,
    [documentId, targetKind, targetId],
  );
  return rows[0] ?? null;
}

export async function invalidateLink(tx: Queryable, id: string): Promise<void> {
  await tx.query(`UPDATE document_links SET t_invalid = now() WHERE id = $1 AND t_invalid IS NULL`, [id]);
}

// ---------------------------------------------------------------------------
// the Files surface
// ---------------------------------------------------------------------------

export interface DocumentListItem {
  id: string;
  filename: string;
  kind: DocumentKind;
  byte_size: number;
  reading: unknown;
  read_failure: string | null;
  text_truncated: boolean;
  t_created: Date;
  /** Display names of the current rows this document is linked to. */
  links: { kind: DocumentLinkTargetKind; id: string; name: string }[];
}

/**
 * Newest first, with each document's links resolved to display names.
 *
 * ONE query for the documents and ONE for their links, not one per document:
 * the list is the page, and N+1 on a page is the shape that stays invisible
 * until someone has uploaded two hundred files.
 */
export async function listRecent(tx: Queryable, limit = 50): Promise<DocumentListItem[]> {
  const { rows: docs } = await tx.query<Omit<DocumentListItem, "links">>(
    `SELECT id, filename, kind, byte_size, reading, read_failure, text_truncated, t_created
       FROM documents_current
      ORDER BY t_created DESC
      LIMIT $1`,
    [limit],
  );
  if (docs.length === 0) return [];

  // Names are read through the _current views: a link to a person merged or
  // undone since shows nothing rather than a stale name.
  const { rows: links } = await tx.query<{
    document_id: string;
    target_kind: DocumentLinkTargetKind;
    target_id: string;
    name: string | null;
  }>(
    `SELECT l.document_id, l.target_kind, l.target_id,
            COALESCE(p.display_name, o.name, pr.name) AS name
       FROM document_links_current l
       LEFT JOIN people_current        p  ON l.target_kind = 'person'       AND p.id  = l.target_id
       LEFT JOIN organizations_current o  ON l.target_kind = 'organization' AND o.id  = l.target_id
       LEFT JOIN projects_current      pr ON l.target_kind = 'project'      AND pr.id = l.target_id
      WHERE l.document_id = ANY($1::uuid[])
      ORDER BY l.t_created`,
    [docs.map((doc) => doc.id)],
  );

  return docs.map((doc) => ({
    ...doc,
    links: links
      .filter((link) => link.document_id === doc.id && link.name !== null)
      .map((link) => ({ kind: link.target_kind, id: link.target_id, name: link.name! })),
  }));
}
